[backup]
command:/usr/local/opnsense/scripts/OPNsense/LocalBackup/backup.sh
parameters:
type:script
message:Creating local configuration backup
description:Create local configuration backup

[restore]
command:/usr/local/opnsense/scripts/OPNsense/LocalBackup/restore.sh
parameters:%s
type:script
message:Restoring local configuration backup %s
description:Restore local configuration backup

[cleanup]
command:/usr/local/opnsense/scripts/OPNsense/LocalBackup/cleanup.sh
parameters:%s
type:script
message:Cleaning up old local backups
description:Cleanup old local backups

[list]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/LocalBackup/list_backups.php
parameters:
type:script_output
message:Listing local backups
description:List local backups

[delete]
command:/usr/local/opnsense/scripts/OPNsense/LocalBackup/delete.sh
parameters:%s
type:script
message:Deleting local backup %s
description:Delete local backup
